Repository itsantonle/se-2144-final-project, pull requests merged in 2024-11, with the labels that each got.

#1 test-branch commit
  client/src/App.tsx
Labels: documentation

#5 add penaltiesController.ts and penaltiesRoute.ts
  server/src/controllers/penaltiesController.ts
  server/src/routes/usersRoute.ts
Labels: enhancement

#12 Auth
  .husky/pre-push
  client/package-lock.json
  client/package.json
  client/public/img/bgWIthDirt.png
  client/public/img/bgWithDirt.svg
  client/src/App.tsx
  client/src/components/Auth/Auth.scss
  client/src/components/Auth/SignIn.tsx
  client/src/components/Auth/SignUp.tsx
  client/src/config/supabase.ts
  client/src/connections/baseURL.ts
  client/src/context/AuthContext.tsx
  client/src/main.tsx
  client/src/services/api.ts
  client/src/services/mutations.ts
  client/src/services/petapi.ts
  client/src/services/queries.ts
  client/src/types/Player.ts
Labels: enhancement, good first issue
